[package]
name = "lru"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"

[profile.release]
debug = 1

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false
